name: Copy Artifacts to VM

on:
  push:
    branches:
      - main

jobs:
  copy_to_vm:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies and Angular CLI
        run: |
          npm install --force
          npm install -g @angular/cli

      - name: Build Angular App
        run: ng build --configuration=production

      - name: Copy Artifacts to VM
        run: |
          echo "Copying Artifacts to VM..."
          echo "${{ secrets.VM_SSH_KEY }}" > ~/.ssh/private_key
          chmod 600 ~/.ssh/private_key
          rsync -e "ssh -i ~/.ssh/private_key" -r dist/ ${{ secrets.VM_USERNAME }}@${{ secrets.VM_HOST }}:/var/www/myapp
