name: Build Angular App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # Set the required Node.js version
          check-latest: true  # Ensure the latest version is used

      - name: Install Dependencies and Angular CLI
        run: |
          npm install
          npm install -g @angular/cli

      - name: Build Angular App
        run: ng build --prod
